### ISSUE TITLE
Glitches Occur When Using Two Realtek Adapters in Monitor Mode with this driver

### ISSUE THREAD

**Issue by reaveruser** [lwfinger/rtw88#355]
When using two Realtek adapters in Monitor Mode (tested with two rtw8814au, or one rtw8814au and one rtw8822b) with this driver, multiple glitches occur. These issues are inconsistent but tend to happen with varying frequency across different channels and bands. The glitches prevent proper scanning, injection, and successful attack execution.

Steps to Reproduce:

- Set both Realtek adapters in monitor mode.
- Use tools like airodump-ng and reaver to test functionality.

Observe the glitches:

- airodump-ng detects only one AP, despite many being available.
- Injection may only work on channels 1–11, or may not work at all.
- Reaver may crash or fail to proceed with the attack.

_**Note:** The issue only occurs when enabling monitor mode for two Realtek adapters (either two rtw8814au or one rtw8814au + one rtw8822b) using this driver._

**Expected Behavior:**

- Both Realtek adapters should function correctly in monitor mode without causing glitches.
- Tools like airodump-ng should display all available APs, and injection should work on all channels.
- No crashes or errors should occur when using tools like Reaver.

**Actual Behavior:**

_Glitches:_

airodump-ng only sees one AP, despite many being available.
Injection works intermittently or only on channels 1–11, or doesn’t work at all.
Reaver crashes or fails to execute correctly.

**No Issues When:**

- Using only one Realtek adapter with this driver (no glitches).
- Using one Mediatek adapter and one Realtek adapter (no glitches).

**Additional Notes:**

When combining the Morrownr 8814au driver for rtw8814au and Kali’s native driver for rtw8822b, there are no issues enabling monitor mode for two Realtek adapters. This combination works as expected without glitches. It is only with this driver.

**Comment by dubhater** [comment]
I wonder if it's the same problem that was recently fixed in rtw89: https://lore.kernel.org/linux-wireless/2goskmst4na36v42p2bs47uernp6kh3gzpadhr3u3r2yvyoxlg@bfprgq2qae7p/

**Comment by reaveruser** [comment]
This could explain why the injection didn't work, even on channels 36 to 48.

This issue has been driving me crazy—not only because it is inconsistent, but also because it only occurs when two Realtek adapters are connected. When only one adapter is attached, the issue does not occur. Disconnecting one adapter immediately resolves the problem. It took me a while to realize it.

If you need assistance with logs or debugging, please let me know, and I’ll be happy to help.

**Comment by reaveruser** [comment]
Is there any chance this issue will be addressed? I must admit that after updating the kernel to version 6.12.38, there have been some improvements, but the problem is not fully resolved.

**Comment by dubhater** [comment]
Someone needs to copy the patch from rtw89.

**Comment by reaveruser** [comment]
The issue has been addressed in kernel version 6.16.8 (I'm unsure if it was fixed in previous versions, as Kali upgraded directly to this one). If I uninstall this driver and use the upstream 6.16 mac80211 driver, the issue is completely resolved. However, the internet feels slower and more laggy. In contrast, using the current driver improves internet speed, but monitor mode performance seems slower; I haven't conducted tests to confirm this yet.

Now that I know the cause of the issue, I can perform further tests and get back to you. Additionally, I noticed that the output from `iw list` shows the same properties for 8822b and 8814au. Is this normal?

```
	max # scan SSIDs: 4
	max scan IEs length: 2243 bytes
	max # sched scan SSIDs: 0
	max # match sets: 0
	Retry short limit: 7
	Retry long limit: 4
	Coverage class: 0 (up to 0m)
	Device supports T-DLS.
	Supported Ciphers:
		* WEP40 (00-0f-ac:1)
		* WEP104 (00-0f-ac:5)
		* TKIP (00-0f-ac:2)
		* CCMP-128 (00-0f-ac:4)
		* CCMP-256 (00-0f-ac:10)
		* GCMP-128 (00-0f-ac:8)
		* GCMP-256 (00-0f-ac:9)
		* CMAC (00-0f-ac:6)
		* CMAC-256 (00-0f-ac:13)
		* GMAC-128 (00-0f-ac:11)
		* GMAC-256 (00-0f-ac:12)
	Available Antennas: TX 0x3 RX 0x3
	Configured Antennas: TX 0x3 RX 0x3
	Supported interface modes:
		 * IBSS
		 * managed
		 * AP
		 * AP/VLAN
		 * monitor
		 * P2P-client
		 * P2P-GO
	Band 1:
		Capabilities: 0x196f
			RX LDPC
			HT20/HT40
			SM Power Save disabled
			RX HT20 SGI
			RX HT40 SGI
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 2 usec (0x04)
		HT Max RX data rate: 300 Mbps
		HT TX/RX MCS rate indexes supported: 0-15, 32
		Bitrates (non-HT):
			* 1.0 Mbps
			* 2.0 Mbps
			* 5.5 Mbps
			* 11.0 Mbps
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 2412.0 MHz [1] (20.0 dBm)
			* 2417.0 MHz [2] (20.0 dBm)
			* 2422.0 MHz [3] (20.0 dBm)
			* 2427.0 MHz [4] (20.0 dBm)
			* 2432.0 MHz [5] (20.0 dBm)
			* 2437.0 MHz [6] (20.0 dBm)
			* 2442.0 MHz [7] (20.0 dBm)
			* 2447.0 MHz [8] (20.0 dBm)
			* 2452.0 MHz [9] (20.0 dBm)
			* 2457.0 MHz [10] (20.0 dBm)
			* 2462.0 MHz [11] (20.0 dBm)
			* 2467.0 MHz [12] (20.0 dBm)
			* 2472.0 MHz [13] (20.0 dBm)
			* 2484.0 MHz [14] (disabled)
	Band 2:
		Capabilities: 0x196f
			RX LDPC
			HT20/HT40
			SM Power Save disabled
			RX HT20 SGI
			RX HT40 SGI
			RX STBC 1-stream
			Max AMSDU length: 7935 bytes
			DSSS/CCK HT40
		Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
		Minimum RX AMPDU time spacing: 2 usec (0x04)
		HT Max RX data rate: 300 Mbps
		HT TX/RX MCS rate indexes supported: 0-15, 32
		VHT Capabilities (0x03d071b2):
			Max MPDU length: 11454
			Supported Channel Width: neither 160 nor 80+80
			RX LDPC
			short GI (80 MHz)
			TX STBC
			SU Beamformee
			MU Beamformee
			+HTC-VHT
		VHT RX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT RX highest supported: 780 Mbps
		VHT TX MCS set:
			1 streams: MCS 0-9
			2 streams: MCS 0-9
			3 streams: not supported
			4 streams: not supported
			5 streams: not supported
			6 streams: not supported
			7 streams: not supported
			8 streams: not supported
		VHT TX highest supported: 780 Mbps
		VHT extended NSS: not supported
		Bitrates (non-HT):
			* 6.0 Mbps
			* 9.0 Mbps
			* 12.0 Mbps
			* 18.0 Mbps
			* 24.0 Mbps
			* 36.0 Mbps
			* 48.0 Mbps
			* 54.0 Mbps
		Frequencies:
			* 5180.0 MHz [36] (23.0 dBm)
			* 5200.0 MHz [40] (23.0 dBm)
			* 5220.0 MHz [44] (23.0 dBm)
			* 5240.0 MHz [48] (23.0 dBm)
			* 5260.0 MHz [52] (20.0 dBm) (radar detection)
			* 5280.0 MHz [56] (20.0 dBm) (radar detection)
			* 5300.0 MHz [60] (20.0 dBm) (radar detection)
			* 5320.0 MHz [64] (20.0 dBm) (radar detection)
			* 5500.0 MHz [100] (26.0 dBm) (radar detection)
			* 5520.0 MHz [104] (26.0 dBm) (radar detection)
			* 5540.0 MHz [108] (26.0 dBm) (radar detection)
			* 5560.0 MHz [112] (26.0 dBm) (radar detection)
			* 5580.0 MHz [116] (26.0 dBm) (radar detection)
			* 5600.0 MHz [120] (26.0 dBm) (radar detection)
			* 5620.0 MHz [124] (26.0 dBm) (radar detection)
			* 5640.0 MHz [128] (26.0 dBm) (radar detection)
			* 5660.0 MHz [132] (26.0 dBm) (radar detection)
			* 5680.0 MHz [136] (26.0 dBm) (radar detection)
			* 5700.0 MHz [140] (26.0 dBm) (radar detection)
			* 5720.0 MHz [144] (13.0 dBm) (radar detection)
			* 5745.0 MHz [149] (13.0 dBm)
			* 5765.0 MHz [153] (13.0 dBm)
			* 5785.0 MHz [157] (13.0 dBm)
			* 5805.0 MHz [161] (13.0 dBm)
			* 5825.0 MHz [165] (13.0 dBm)
	Supported commands:
		 * new_interface
		 * set_interface
		 * new_key
		 * start_ap
		 * new_station
		 * new_mpath
		 * set_mesh_config
		 * set_bss
		 * authenticate
		 * associate
		 * deauthenticate
		 * disassociate
		 * join_ibss
		 * join_mesh
		 * remain_on_channel
		 * set_tx_bitrate_mask
		 * frame
		 * frame_wait_cancel
		 * set_wiphy_netns
		 * set_channel
		 * tdls_mgmt
		 * tdls_oper
		 * probe_client
		 * set_noack_map
		 * register_beacons
		 * start_p2p_device
		 * set_mcast_rate
		 * connect
		 * disconnect
		 * set_qos_map
		 * set_multicast_to_unicast
		 * set_sar_specs
		 * assoc_mlo_reconf
	software interface modes (can always be added):
		 * AP/VLAN
		 * monitor
	valid interface combinations:
		 * #{ managed } <= 1, #{ AP, P2P-client, P2P-GO } <= 1,
		   total <= 2, #channels <= 1
	HT Capability overrides:
		 * MCS: ff ff ff ff ff ff ff ff ff ff
		 * maximum A-MSDU length
		 * supported channel width
		 * short GI for 40 MHz
		 * max A-MPDU length exponent
		 * min MPDU start spacing
	Device supports TX status socket option.
	Device supports HT-IBSS.
	Device supports SAE with AUTHENTICATE command
	Device supports scan flush.
	Device supports per-vif TX power setting
	Driver supports full state transitions for AP/GO clients
	Driver supports a userspace MPM
	Device supports configuring vdev MAC-addr on create.
	Device supports randomizing MAC-addr in scans.
	max # scan plans: 1
	max scan plan interval: -1
	max scan plan iterations: 0
	Supported TX frame types:
		 * IBSS: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
		 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
	Supported RX frame types:
		 * IBSS: 0x40 0xb0 0xc0 0xd0
		 * managed: 0x40 0xb0 0xd0
		 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * mesh point: 0xb0 0xc0 0xd0
		 * P2P-client: 0x40 0xd0
		 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
		 * P2P-device: 0x40 0xb0 0xd0
	Supported extended features:
		* [ RRM ]: RRM
		* [ SET_SCAN_DWELL ]: scan dwell setting
		* [ FILS_STA ]: STA FILS (Fast Initial Link Setup)
		* [ CONTROL_PORT_OVER_NL80211 ]: control port over nl80211
		* [ TXQS ]: FQ-CoDel-enabled intermediate TXQs
		* [ SCAN_RANDOM_SN ]: use random sequence numbers in scans
		* [ CAN_REPLACE_PTK0 ]: can safely replace PTK 0 when rekeying
		* [ CONTROL_PORT_NO_PREAUTH ]: disable pre-auth over nl80211 control port support
		* [ DEL_IBSS_STA ]: deletion of IBSS station support
		* [ SCAN_FREQ_KHZ ]: scan on kHz frequency support
		* [ CONTROL_PORT_OVER_NL80211_TX_STATUS ]: tx status for nl80211 control port support
		* [ POWERED_ADDR_CHANGE ]: can change MAC address while up
```

**Comment by reaveruser** [comment]
I will close this bug because the issue with having two Realtek adapters connected simultaneously is fully resolved in kernel 6.16. However, the lags I am experiencing occur even when only one adapter is connected. Therefore, I will need to file a separate bug for this issue.

**Comment by reaveruser** [comment]
I closed this bug earlier thinking kernel 6.16 fixed it, but that was incorrect. The issue reproduces when both Realtek adapters are connected through a USB‑C hub to USB 3.0. Connecting the adapters to two separate USB 3.0 ports (not via the hub) or using a USB 3.0 hub avoids the glitches. **Using the older Morrownr 8814au driver with the same USB‑C hub also avoids the issue, so this regression appears specific to this driver**. The USB‑C hub reproduces the problem on kernels 6.16 and 6.17. I will reopen this issue for investigation — please check USB‑3/USB‑C hub handling in this driver (endpoint/URB timing, power-management). I can attach dmesg, lsusb and usbmon traces if helpful.

**Comment by reaveruser** [comment]
For testing I connected the two adapters to separate USB‑C hubs — no issues. The problem only occurs when both adapters are connected to the same USB‑C hub. **Setting switch_usb_mode=n fixes the issue**. Unlike https://github.com/lwfinger/rtw88/issues/402, this occurred on kernel 6.11.

@dubhater  It’s possible the older Morrownr 8814au driver avoids this because it lacks a USB‑3 mode. My recommendation: switch_usb_mode=n should be the default value until the USB‑3 issue is addressed.

I will close this bug; if I encounter the issue again I will reopen it for documentation only.

**Comment by dubhater** [comment]
> I wonder if it's the same problem that was recently fixed in rtw89: https://lore.kernel.org/linux-wireless/2goskmst4na36v42p2bs47uernp6kh3gzpadhr3u3r2yvyoxlg@bfprgq2qae7p/

I pushed a fix for that problem. (It won't help the RTL8822BU in USB 3 mode, or the trouble caused by that external hub.)

**Comment by dubhater** [comment]
> Additionally, I noticed that the output from `iw list` shows the same properties for 8822b and 8814au. Is this normal?
> 

It's normal when the RTL8814AU is in USB 2 mode. rtw88 pretends it's a 2T2R device. The official driver pretends it's a 2T3R device, but that would have been more work to implement in rtw88.

The reason why it can't be allowed to transmit 3 spatial streams in USB 2 mode is probably that 500 mA is not enough.
